--[[
XIIM Constants Module
Contains all constants and lookup tables
]]--

local constants = {}

-- Container definitions (verified from scan results)
constants.CONTAINERS = {
    [0] = { id=0, name='Inventory' },
    [1] = { id=1, name='Safe' },
    [2] = { id=2, name='Storage' },
    [3] = { id=3, name='Temporary' },
    [4] = { id=4, name='Locker' },
    [5] = { id=5, name='Satchel' },
    [6] = { id=6, name='Sack' },
    [7] = { id=7, name='Case' },
    [8] = { id=8, name='Wardrobe' },
    [9]= { id=9, name='Safe2' },
    [10]= { id=10, name='Wardrobe2' },
    [11]= { id=11, name='Wardrobe3' },
    [12]= { id=12, name='Wardrobe4' },
    [13]= { id=13, name='Wardrobe5' },
    [14]= { id=14, name='Wardrobe6' },
    [15]= { id=15, name='Wardrobe7' },
    [16]= { id=16, name='Wardrobe8' }
}

-- Equipment slot definitions
constants.EQUIPMENT_SLOTS = {
    [0] = 'Main',
    [1] = 'Sub',
    [2] = 'Range',
    [3] = 'Ammo',
    [4] = 'Head',
    [5] = 'Body',
    [6] = 'Hands',
    [7] = 'Legs',
    [8] = 'Feet',
    [9] = 'Neck',
    [10] = 'Waist',
    [11] = 'Ear1',
    [12] = 'Ear2',
    [13] = 'Ring1',
    [14] = 'Ring2',
    [15] = 'Back',
}

-- Augment path definitions (for Delve/Dynamis items)
constants.AUGMENT_PATHS = {
    [1] = 'A',
    [2] = 'B',
    [3] = 'C',
    [4] = 'D'
}

-- Basic augments lookup table (Oseem/Magian style)
-- Maps augment ID (0-2047) to stat definitions with offset and multiplier
constants.BASIC_AUGMENTS = {
    [1] = { Stat='HP', Offset=1},
    [2] = { Stat='HP', Offset=33},
    [3] = { Stat='HP', Offset=65},
    [4] = { Stat='HP', Offset=97},
    [5] = { Stat='HP', Offset=1, Multiplier=-1},
    [6] = { Stat='HP', Offset=33, Multiplier=-1},
    [7] = { Stat='HP', Offset=65, Multiplier=-1},
    [8] = { Stat='HP', Offset=97, Multiplier=-1},
    [9] = { Stat='MP', Offset=1},
    [10] = { Stat='MP', Offset=33},
    [11] = { Stat='MP', Offset=65},
    [12] = { Stat='MP', Offset=97},
    [13] = { Stat='MP', Offset=1, Multiplier=-1},
    [14] = { Stat='MP', Offset=33, Multiplier=-1},
    [15] = { Stat='MP', Offset=65, Multiplier=-1},
    [16] = { Stat='MP', Offset=97, Multiplier=-1},
    [17] = { Multi=true, [1] = { Stat='HP', Offset=1}, [2] = { Stat='MP', Offset=1} },
    [18] = { Multi=true, [1] = { Stat='HP', Offset=33}, [2] = { Stat='MP', Offset=33} },
    [19] = { Multi=true, [1] = { Stat='HP', Offset=1}, [2] = { Stat='MP', Offset=1, Multiplier=-1} },
    [20] = { Multi=true, [1] = { Stat='HP', Offset=33}, [2] = { Stat='MP', Offset=33, Multiplier=-1} },
    [21] = { Multi=true, [1] = { Stat='HP', Offset=1, Multiplier=-1}, [2] = { Stat='MP', Offset=1} },
    [22] = { Multi=true, [1] = { Stat='HP', Offset=33, Multiplier=-1}, [2] = { Stat='MP', Offset=33} },
    [23] = { Stat='Accuracy', Offset=1},
    [24] = { Stat='Accuracy', Offset=1, Multiplier=-1},
    [25] = { Stat='Attack', Offset=1},
    [26] = { Stat='Attack', Offset=1, Multiplier=-1},
    [27] = { Stat='Rng.Acc.', Offset=1},
    [28] = { Stat='Rng.Acc.', Offset=1, Multiplier=-1},
    [29] = { Stat='Rng.Atk.', Offset=1},
    [30] = { Stat='Rng.Atk.', Offset=1, Multiplier=-1},
    [31] = { Stat='Evasion', Offset=1},
    [32] = { Stat='Evasion', Offset=1, Multiplier=-1},
    [33] = { Stat='DEF', Offset=1},
    [34] = { Stat='DEF', Offset=1, Multiplier=-1},
    [35] = { Stat='Mag. Acc.', Offset=1},
    [36] = { Stat='Mag. Acc.', Offset=1, Multiplier=-1},
    [37] = { Stat='Mag. Evasion', Offset=1},
    [38] = { Stat='Mag. Evasion', Offset=1, Multiplier=-1},
    [39] = { Stat='Enmity', Offset=1},
    [40] = { Stat='Enmity', Offset=1, Multiplier=-1},
    [41] = { Stat='Crit.hit rate', Offset=1},
    [42] = { Stat='Enemy crit. hit rate ', Offset=1, Multiplier=-1},
    [43] = { Stat='"Charm"', Offset=1},
    [44] = { Multi=true, [1] = { Stat='"Store TP"', Offset=1}, [2] = { Stat='"Subtle Blow"', Offset=1} },
    [45] = { Stat='DMG:', Offset=1},
    [46] = { Stat='DMG:', Offset=1, Multiplier=-1},
    [47] = { Stat='Delay:', Offset=1, Percent=true},
    [48] = { Stat='Delay:', Offset=1, Multiplier=-1, Percent=true},
    [49] = { Stat='Haste', Offset=1},
    [50] = { Stat='"Slow"', Offset=1},
    [51] = { Stat='HP recovered while healing ', Offset=1},
    [52] = { Stat='MP recovered while healing ', Offset=1},
    [53] = { Stat='Spell interruption rate down ', Offset=1, Multiplier=-1, Percent=true},
    [54] = { Stat='Phys. dmg. taken ', Offset=1, Multiplier=-1, Percent=true},
    [55] = { Stat='Magic dmg. taken ', Offset=1, Multiplier=-1, Percent=true},
    [56] = { Stat='Breath dmg. taken ', Offset=1, Multiplier=-1, Percent=true},
    [57] = { Stat='Magic crit. hit rate ', Offset=1},
    [58] = { Stat='"Mag.Def.Bns."', Offset=1, Multiplier=-1},
    [59] = { Stat='Latent effect: "Regain"', Offset=1},
    [60] = { Stat='Latent effect: "Refresh"', Offset=1},
    [61] = { Stat='Occ. inc. resist. to stat. ailments ', Offset=1},
    [62] = { Stat='Accuracy', Offset=33},
    [63] = { Stat='Rng.Acc.', Offset=33},
    [64] = { Stat='Mag. Acc.', Offset=33},
    [65] = { Stat='Attack', Offset=33},
    [66] = { Stat='Rng.Atk.', Offset=33},
    [67] = { Stat='All Songs', Offset=1},
    [68] = { Multi=true, [1] = { Stat='Accuracy', Offset=1}, [2] = { Stat='Attack', Offset=1} },
    [69] = { Multi=true, [1] = { Stat='Rng.Acc.', Offset=1}, [2] = { Stat='Rng.Atk.', Offset=1} },
    [70] = { Multi=true, [1] = { Stat='Mag. Acc.', Offset=1}, [2] = { Stat='"Mag. Atk. Bns."', Offset=1} },
    [71] = { Stat='Damage taken', Offset=1, Multiplier=-1, Percent=true},
    [74] = { Stat='Cap. Point', Offset=1, Percent=true},
    [75] = { Stat='Cap. Point', Offset=33, Percent=true},
    [76] = { Stat='DMG:', Offset=33},
    [77] = { Stat='Delay:', Offset=33, Multiplier=-1, Percent=true},
    [78] = { Stat='HP', Offset=1, Multiplier=2},
    [79] = { Stat='HP', Offset=1, Multiplier=3},
    [80] = { Multi=true, [1] = { Stat='Mag. Acc.', Offset=1}, [2] = { Stat='Magic Damage', Offset=1} },
    [81] = { Multi=true, [1] = { Stat='Evasion', Offset=1}, [2] = { Stat='Mag. Evasion', Offset=1} },
    [82] = { Stat='MP', Offset=1, Multiplier=2},
    [83] = { Stat='MP', Offset=1, Multiplier=3},
    [96] = { Multi=true, [1] = { Stat='Pet: Accuracy', Offset=1}, [2] = { Stat='Pet: Rng. Acc.', Offset=1} },
    [97] = { Multi=true, [1] = { Stat='Pet: Attack', Offset=1}, [2] = { Stat='Pet: Rng.Atk.', Offset=1} },
    [98] = { Stat='Pet: Evasion', Offset=1},
    [99] = { Stat='Pet: DEF', Offset=1},
    [100] = { Stat='Pet: Mag. Acc.', Offset=1},
    [101] = { Stat='Pet: "Mag. Atk. Bns."', Offset=1},
    [102] = { Stat='Pet: Crit.hit rate ', Offset=1},
    [103] = { Stat='Pet: Enemy crit. hit rate ', Offset=1, Multiplier=-1},
    [104] = { Stat='Pet: Enmity', Offset=1},
    [105] = { Stat='Pet: Enmity', Offset=1, Multiplier=-1},
    [133] = { Stat='"Mag. Atk. Bns."', Offset=1},
    [134] = { Stat='"Mag.Def.Bns."', Offset=1},
    [137] = { Stat='"Regen"', Offset=1},
    [138] = { Stat='"Refresh"', Offset=1},
    [139] = { Stat='"Rapid Shot"', Offset=1},
    [140] = { Stat='"Fast Cast"', Offset=1},
    [141] = { Stat='"Conserve MP"', Offset=1},
    [142] = { Stat='"Store TP"', Offset=1},
    [143] = { Stat='"Dbl.Atk."', Offset=1},
    [144] = { Stat='"Triple Atk."', Offset=1},
    [145] = { Stat='"Counter"', Offset=1},
    [146] = { Stat='"Dual Wield"', Offset=1},
    [147] = { Stat='"Treasure Hunter"', Offset=1},
    [148] = { Stat='"Gilfinder"', Offset=1},
    [151] = { Stat='"Martial Arts"', Offset=1},
    [153] = { Stat='"Shield Mastery"', Offset=1},
    [176] = { Stat='"Resist Sleep"', Offset=1},
    [177] = { Stat='"Resist Poison"', Offset=1},
    [178] = { Stat='"Resist Paralyze"', Offset=1},
    [179] = { Stat='"Resist Blind"', Offset=1},
    [180] = { Stat='"Resist Silence"', Offset=1},
    [181] = { Stat='"Resist Petrify"', Offset=1},
    [182] = { Stat='"Resist Virus"', Offset=1},
    [183] = { Stat='"Resist Curse"', Offset=1},
    [184] = { Stat='"Resist Stun"', Offset=1},
    [185] = { Stat='"Resist Bind"', Offset=1},
    [186] = { Stat='"Resist Gravity"', Offset=1},
    [187] = { Stat='"Resist Slow"', Offset=1},
    [188] = { Stat='"Resist Charm"', Offset=1},
    [194] = { Stat='"Kick Attacks"', Offset=1},
    [195] = { Stat='"Subtle Blow"', Offset=1},
    [198] = { Stat='"Zanshin"', Offset=1},
    [211] = { Stat='"Snapshot"', Offset=1},
    [212] = { Stat='"Recycle"', Offset=1},
    [215] = { Stat='"Ninja tool expertise"', Offset=1},
    [233] = { Stat='"Blood Boon"', Offset=1},
    [237] = { Stat='"Occult Acumen"', Offset=1},
    [257] = { Stat='Hand-to-Hand skill ', Offset=1},
    [258] = { Stat='Dagger skill ', Offset=1},
    [259] = { Stat='Sword skill ', Offset=1},
    [260] = { Stat='Great Sword skill ', Offset=1},
    [261] = { Stat='Axe skill ', Offset=1},
    [262] = { Stat='Great Axe skill ', Offset=1},
    [263] = { Stat='Scythe skill ', Offset=1},
    [264] = { Stat='Polearm skill ', Offset=1},
    [265] = { Stat='Katana skill ', Offset=1},
    [266] = { Stat='Great Katana skill ', Offset=1},
    [267] = { Stat='Club skill ', Offset=1},
    [268] = { Stat='Staff skill ', Offset=1},
    [278] = { Stat='Melee skill ', Offset=1},
    [279] = { Stat='Ranged skill ', Offset=1},
    [280] = { Stat='Magic skill ', Offset=1},
    [281] = { Stat='Archery skill ', Offset=1},
    [282] = { Stat='Marksmanship skill ', Offset=1},
    [283] = { Stat='Throwing skill ', Offset=1},
    [286] = { Stat='Shield skill ', Offset=1},
    [288] = { Stat='Divine magic skill ', Offset=1},
    [289] = { Stat='Healing magic skill ', Offset=1},
    [290] = { Stat='Enha.mag. skill ', Offset=1},
    [291] = { Stat='Enfb.mag. skill ', Offset=1},
    [292] = { Stat='Elem. magic skill ', Offset=1},
    [293] = { Stat='Dark magic skill ', Offset=1},
    [294] = { Stat='Summoning magic skill ', Offset=1},
    [295] = { Stat='Ninjutsu skill ', Offset=1},
    [296] = { Stat='Singing skill ', Offset=1},
    [297] = { Stat='String instrument skill ', Offset=1},
    [298] = { Stat='Wind instrument skill ', Offset=1},
    [299] = { Stat='Blue Magic skill ', Offset=1},
    [300] = { Stat='Geomancy Skill ', Offset=1},
    [301] = { Stat='Handbell Skill ', Offset=1},
    [320] = { Stat='"Blood Pact" ability delay ', Offset=1, Multiplier=-1},
    [321] = { Stat='"Avatar perpetuation cost" ', Offset=1, Multiplier=-1},
    [322] = { Stat='Song spellcasting time ', Offset=1, Multiplier=-1, Percent=true},
    [323] = { Stat='"Cure" spellcasting time ', Offset=1, Multiplier=-1, Percent=true},
    [324] = { Stat='"Call Beast" ability delay ', Offset=1, Multiplier=-1},
    [325] = { Stat='"Quick Draw" ability delay ', Offset=1, Multiplier=-1},
    [326] = { Stat='Weapon Skill Acc.', Offset=1},
    [327] = { Stat='Weapon skill damage ', Offset=1, Percent=true},
    [328] = { Stat='Crit. hit damage ', Offset=1, Percent=true},
    [329] = { Stat='"Cure" potency ', Offset=1, Percent=true},
    [330] = { Stat='"Waltz" potency ', Offset=1, Percent=true},
    [331] = { Stat='"Waltz" ability delay ', Offset=1, Multiplier=-1},
    [332] = { Stat='Sklchn.dmg.', Offset=1, Percent=true},
    [333] = { Stat='"Conserve TP"', Offset=1},
    [334] = { Stat='Magic burst dmg.', Offset=1, Percent=true},
    [335] = { Stat='Mag. crit. hit dmg. ', Offset=1, Percent=true},
    [336] = { Stat='"Sic" and "Ready" ability delay ', Offset=1, Multiplier=-1},
    [337] = { Stat='Song recast delay ', Offset=1, Multiplier=-1},
    [338] = { Stat='"Barrage"', Offset=1},
    [339] = { Stat='"Elemental Siphon"', Offset=1, Multiplier=5},
    [340] = { Stat='"Phantom Roll" ability delay ', Offset=1, Multiplier=-1},
    [341] = { Stat='"Repair" potency ', Offset=1, Percent=true},
    [342] = { Stat='"Waltz" TP cost ', Offset=1, Multiplier=-1},
    [343] = { Stat='"Drain" and "Aspir" potency ', Offset=1},
    [350] = { Stat='Occ. maximizes magic accuracy ', Offset=1, Percent=true},
    [351] = { Stat='Occ. quickens spellcasting ', Offset=1, Percent=true},
    [352] = { Stat='Occ. grants dmg. bonus based on TP ', Offset=1, Percent=true},
    [353] = { Stat='TP Bonus ', Offset=1, Multiplier=50},
    [354] = { Stat='Quadruple Attack ', Offset=1},
    [356] = { Stat='Potency of "Cure" effect received', Offset=1, Percent=true},
    [360] = { Stat='Save TP ', Offset=1, Multiplier=10},
    [362] = { Stat='Magic Damage ', Offset=1},
    [363] = { Stat='Chance of successful block ', Offset=1},
    [366] = { Stat='Blood Pact ab. del. II ', Offset=1, Multiplier=-1},
    [368] = { Stat='Phalanx ', Offset=1},
    [369] = { Stat='Blood Pact Dmg.', Offset=1},
    [370] = { Stat='"Rev. Flourish"', Offset=1},
    [371] = { Stat='"Regen" potency', Offset=1},
    [372] = { Stat='"Embolden"', Offset=1},
    [512] = { Stat='STR', Offset=1},
    [513] = { Stat='DEX', Offset=1},
    [514] = { Stat='VIT', Offset=1},
    [515] = { Stat='AGI', Offset=1},
    [516] = { Stat='INT', Offset=1},
    [517] = { Stat='MND', Offset=1},
    [518] = { Stat='CHR', Offset=1},
    [519] = { Stat='STR', Offset=1, Multiplier=-1},
    [520] = { Stat='DEX', Offset=1, Multiplier=-1},
    [521] = { Stat='VIT', Offset=1, Multiplier=-1},
    [522] = { Stat='AGI', Offset=1, Multiplier=-1},
    [523] = { Stat='INT', Offset=1, Multiplier=-1},
    [524] = { Stat='MND', Offset=1, Multiplier=-1},
    [525] = { Stat='CHR', Offset=1, Multiplier=-1},
    [550] = { Multi=true, [1] = { Stat='STR', Offset=1}, [2] = { Stat='DEX', Offset=1} },
    [551] = { Multi=true, [1] = { Stat='STR', Offset=1}, [2] = { Stat='VIT', Offset=1} },
    [552] = { Multi=true, [1] = { Stat='STR', Offset=1}, [2] = { Stat='AGI', Offset=1} },
    [553] = { Multi=true, [1] = { Stat='DEX', Offset=1}, [2] = { Stat='AGI', Offset=1} },
    [554] = { Multi=true, [1] = { Stat='INT', Offset=1}, [2] = { Stat='MND', Offset=1} },
    [555] = { Multi=true, [1] = { Stat='MND', Offset=1}, [2] = { Stat='CHR', Offset=1} },
    [556] = { Multi=true, [1] = { Stat='INT', Offset=1}, [2] = { Stat='MND', Offset=1}, [3] = { Stat='CHR', Offset=1} },
    [557] = { Multi=true, [1] = { Stat='STR', Offset=1}, [2] = { Stat='CHR', Offset=1} },
    [558] = { Multi=true, [1] = { Stat='STR', Offset=1}, [2] = { Stat='INT', Offset=1} },
    [559] = { Multi=true, [1] = { Stat='STR', Offset=1}, [2] = { Stat='MND', Offset=1} },
    [768] = { Stat='Fire resistance', Offset=1},
    [769] = { Stat='Ice resistance', Offset=1},
    [770] = { Stat='Wind resistance', Offset=1},
    [771] = { Stat='Earth resistance', Offset=1},
    [772] = { Stat='Lightning resistance', Offset=1},
    [773] = { Stat='Water resistance', Offset=1},
    [774] = { Stat='Light resistance', Offset=1},
    [775] = { Stat='Dark resistance', Offset=1},
    [776] = { Stat='Fire resistance', Offset=1, Multiplier=-1},
    [777] = { Stat='Ice resistance', Offset=1, Multiplier=-1},
    [778] = { Stat='Wind resistance', Offset=1, Multiplier=-1},
    [779] = { Stat='Earth resistance', Offset=1, Multiplier=-1},
    [780] = { Stat='Lightning resistance', Offset=1, Multiplier=-1},
    [781] = { Stat='Water resistance', Offset=1, Multiplier=-1},
    [782] = { Stat='Light resistance', Offset=1, Multiplier=-1},
    [783] = { Stat='Dark resistance', Offset=1, Multiplier=-1},
    [2047] = { Stat='???'},
}

-- Delve augments lookup table  
constants.DELVE_AUGMENTS = {
    [2] = { Stat='HP', Offset=1},
    [3] = { Stat='HP', Offset=256},
    [4] = { Stat='MP', Offset=1},
    [5] = { Stat='MP', Offset=256},
    [8] = { Stat='Attack', Offset=1},
    [9] = { Stat='Attack', Offset=256},
    [10] = { Stat='Rng.Atk.', Offset=1},
    [11] = { Stat='Rng.Atk.', Offset=256},
    [12] = { Stat='Accuracy', Offset=1},
    [13] = { Stat='Accuracy', Offset=256},
    [14] = { Stat='Rng.Acc.', Offset=1},
    [15] = { Stat='Rng.Acc.', Offset=256},
    [16] = { Stat='DEF', Offset=1},
    [17] = { Stat='DEF', Offset=256},
    [18] = { Stat='Evasion', Offset=1},
    [19] = { Stat='Evasion', Offset=256},
    [20] = { Stat='"Mag. Atk. Bns."', Offset=1},
    [21] = { Stat='"Mag. Atk. Bns."', Offset=256},
    [22] = { Stat='"Mag.Def.Bns."', Offset=1},
    [23] = { Stat='"Mag.Def.Bns."', Offset=256},
    [24] = { Stat='Mag. Acc.', Offset=1},
    [25] = { Stat='Mag. Acc.', Offset=256},
    [26] = { Stat='Mag. Evasion', Offset=1},
    [27] = { Stat='Mag. Evasion', Offset=256},
    [28] = { Stat='DMG:', Offset=1},
    [29] = { Stat='DMG:', Offset=256},
    [114] = { Stat='Weapon skill damage ', Offset=1, Percent=true},
    [115] = { Stat='Magic damage', Offset=1},
    [116] = { Stat='Blood Pact Dmg.', Offset=1 },
    [117] = { Stat='"Avatar perpetuation cost"', Offset=1},
    [118] = { Stat='"Blood Pact" ability delay', Offset=1},
    [119] = { Stat='Haste', Offset=1, Percent=true},
    [120] = { Stat='Enmity', Offset=1},
    [121] = { Stat='Enmity', Offset=1, Multiplier=-1},
    [122] = { Stat='Crit. hit rate', Offset=1, Percent=true},
    [123] = { Stat='"Cure" spellcasting time ', Offset=1, Multiplier=-1, Percent=true},
    [124] = { Stat='"Cure" potency ', Offset=1, Percent=true},
    [125] = { Stat='"Refresh"', Offset=1},
    [126] = { Stat='Spell interruption rate down ', Offset=1, Percent=true},
    [127] = { Stat='Potency of "Cure" effect received ', Offset=1, Percent=true},
    [128] = { Stat='Pet: "Mag. Atk. Bns."', Offset=1},
    [129] = { Stat='Pet: Mag. Acc.', Offset=1},
    [130] = { Stat='Pet: Attack', Offset=1},
    [131] = { Stat='Pet: Accuracy', Offset=1},
    [132] = { Stat='Pet: Enmity', Offset=1},
    [133] = { Stat='Pet: Enmity', Offset=1},
    [134] = { Stat='Pet: HP', Offset=1},
    [135] = { Stat='Pet: MP', Offset=1},
    [136] = { Stat='Pet: STR', Offset=1},
    [137] = { Stat='Pet: DEX', Offset=1},
    [138] = { Stat='Pet: VIT', Offset=1},
    [139] = { Stat='Pet: AGI', Offset=1},
    [140] = { Stat='Pet: INT', Offset=1},
    [141] = { Stat='Pet: MND', Offset=1},
    [142] = { Stat='Pet: CHR', Offset=1},
    [152] = { Stat='Pet: "Dbl. Atk."', Offset=1},
    [153] = { Stat='Pet: Damage taken ', Offset=1, Multiplier=-1, Percent=true},
    [154] = { Stat='Pet: "Regen"', Offset=1},
    [155] = { Stat='Pet: Haste', Offset=1, Percent=true},
    [156] = { Stat='Automaton: "Cure" potency ', Offset=1, Percent=true},
    [157] = { Stat='Automaton: "Fast Cast"', Offset=1},
    [171] = { Stat='"Dual Wield"', Offset=1},
    [172] = { Stat='Damage Taken ', Offset=1, Multiplier=-1, Percent=true},
    [173] = { Stat='All songs ', Offset=1},
    [177] = { Stat='"Conserve MP"', Offset=1},
    [178] = { Stat='"Counter"', Offset=1},
    [179] = { Stat='"Triple Atk."', Offset=1},
    [180] = { Stat='"Fast Cast"', Offset=1},
    [181] = { Stat='"Blood Boon"', Offset=1},
    [182] = { Stat='"Subtle Blow"', Offset=1},
    [183] = { Stat='"Rapid Shot"', Offset=1},
    [184] = { Stat='"Recycle"', Offset=1},
    [185] = { Stat='"Store TP"', Offset=1},
    [186] = { Stat='"Dbl.Atk."', Offset=1},
    [187] = { Stat='"Snapshot"', Offset=1},
    [188] = { Stat='Phys. dmg. taken ', Offset=1, Multiplier=-1},
    [189] = { Stat='Magic dmg. taken ', Offset=1, Multiplier=-1},
    [190] = { Stat='Breath dmg. taken ', Offset=1, Multiplier=-1},
    [191] = { Stat='STR', Offset=1},
    [192] = { Stat='DEX', Offset=1},
    [193] = { Stat='VIT', Offset=1},
    [194] = { Stat='AGI', Offset=1},
    [195] = { Stat='INT', Offset=1},
    [196] = { Stat='MND', Offset=1},
    [197] = { Stat='CHR', Offset=1},
    [206] = { Multi=true, [1] = { Stat='STR', Offset=1}, [2] = { Stat='DEX', Offset=1}, [3] = { Stat='VIT', Offset=1}, [4] = { Stat='AGI', Offset=1}, [5] = { Stat='INT', Offset=1}, [6] = { Stat='MND', Offset=1}, [7] = { Stat='CHR', Offset=1} },
    [208] = { Stat='Hand-to-Hand skill ', Offset=1},
    [209] = { Stat='Dagger skill ', Offset=1},
    [210] = { Stat='Sword skill ', Offset=1},
    [211] = { Stat='Great Sword skill ', Offset=1},
    [212] = { Stat='Axe skill ', Offset=1},
    [213] = { Stat='Great Axe skill ', Offset=1},
    [214] = { Stat='Scythe skill ', Offset=1},
    [215] = { Stat='Polearm skill ', Offset=1},
    [216] = { Stat='Katana skill ', Offset=1},
    [217] = { Stat='Great Katana skill ', Offset=1},
    [218] = { Stat='Club skill ', Offset=1},
    [219] = { Stat='Staff skill ', Offset=1},
    [229] = { Stat='Melee skill ', Offset=1},
    [230] = { Stat='Ranged skill ', Offset=1},
    [231] = { Stat='Magic skill ', Offset=1},
    [232] = { Stat='Archery skill ', Offset=1},
    [233] = { Stat='Marksmanship skill ', Offset=1},
    [234] = { Stat='Throwing skill ', Offset=1},
    [237] = { Stat='Shield skill ', Offset=1},
    [239] = { Stat='Divine magic skill ', Offset=1},
    [240] = { Stat='Healing magic skill ', Offset=1},
    [241] = { Stat='Enha.mag. skill ', Offset=1},
    [242] = { Stat='Enfb.mag. skill ', Offset=1},
    [243] = { Stat='Elem. magic skill ', Offset=1},
    [244] = { Stat='Dark magic skill ', Offset=1},
    [245] = { Stat='Summoning magic skill ', Offset=1},
    [246] = { Stat='Ninjutsu skill ', Offset=1},
    [247] = { Stat='Singing skill ', Offset=1},
    [248] = { Stat='String instrument skill ', Offset=1},
    [249] = { Stat='Wind instrument skill ', Offset=1},
    [250] = { Stat='Blue Magic skill ', Offset=1},
    [251] = { Stat='Geomancy Skill ', Offset=1},
    [252] = { Stat='Handbell Skill', Offset=1},
}

return constants
